apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-runner-system

resources:
- github.com/actions-runner-controller/actions-runner-controller/config//github-webhook-server?ref=v0.22.2
- ingress.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/actions-runner-controller/actions-runner-controller/v0.22.2/config/default/gh-webhook-server-auth-proxy-patch.yaml
