name: Test Deploy with private runner

on:
  workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
  ARM_USE_MSI: true

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Setup Nodejs
      uses: actions/setup-node@v1
    - name: Install TF
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0
    - name: Run TF apply
      run: |
        mkdir test
        cd test

        cat <<EOF >main.tf
        terraform {
          required_providers {
            azurerm = {
              source  = "hashicorp/azurerm"
              version = "~> 2.80"
            }
          }
        }

        provider "azurerm" {
          features {}
        }

        resource "azurerm_resource_group" "test_runner" {
          name     = "test-runner"
          location = "West Europe"
        }
        EOF

        terraform init
        terraform apply -auto-approve
        terraform destroy -auto-approve
